redis: &redis
  redis_server: 'localhost'
  redis_port: 6378
  redis_db_num: 1
  redis_namespace: 'redis_sidekiq'
#  user_name: dingxu
#  user_password: sidekiq

development:
  <<: *redis

production:
  <<: *redis
